development:
  adapter: postgresql
  encoding: unicode
  database: enalytics_development
  pool: 5
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: heat
  pool: 10
  min_messages: warning
